# Generated by Django 5.0.6 on 2025-03-04 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_usermodel_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPeriodModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('periodCycle', models.IntegerField()),
                ('periodLength', models.IntegerField()),
                ('periodDate', models.DateField()),
                ('periodstress', models.CharField(max_length=200)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usermodel')),
            ],
        ),
    ]
