# Generated by Django 5.0.6 on 2025-03-05 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userperiodmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userperiodmodel',
            old_name='periodstress',
            new_name='periodStress',
        ),
    ]
